name: artefacts
on:
  workflow_dispatch:

jobs:
  Download-the-artefacts:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: installing pip-audit
        run: pip install pip-audit

      - name: running pip-audit
        run: pip-audit -r requirements.txt

      - name: check the syntaxes
        run: flake8 app.py

      - name: artefacts
        uses: actions/upload-artifact@v4
