name: Hello Workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "This job should run only on the timestamp"
        required: true
        default: greet
        type: choice
        options:
          - greet
          - timestamp
          - default

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: says hello
        run: echo "Hello from GitHub Actions!"
  timestamp:
    runs-on: ubuntu-latest
    if: inputs.environment == 'timestamp'
    steps:
      - name: checks the time & date
        run: date
      - name: branch name
        run: echo "Current branch is ${{ github.ref }}"
      - name: list the files in the repo
        run: ls -la
      - name: prints the runner's OS
        run: echo "Running on ${{ runner.os }}"
