name: manual workflow
on:
 workflow_dispatch:
  inputs:
    environments:
      description: "Enter the Environment"
      required: true
      default: stage
jobs:
  manual-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment
        run: echo "Deploying to environment: ${{ github.event.inputs.environment }}"
  
