name: manual
on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Select the environment to deploy to"
                required: true
                default: "staging"
                type: choice
                options:
                    - staging
                    - production
jobs:
    manual-deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.inputs.environment == 'staging' }}
        steps:
            - name: Manual deployment
              run: echo "Deploying to ${{ github.event.inputs.environment }} environment!"
