name: matrix-job
on:
  push:
    branches: [main]
jobs:
  matrix-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: ["3.11", "3.12", "3.13"]

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-versions: ${{ matrix.python-versions }}
      - name: Check Python version
        run: python --version
