name: Run Tests

on:
  workflow_dispatch

jobs:
  test-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run Test Script
        run: python scripts/test_script.py
