name: scheduled trigger
on:
    schedule:
        - cron: "0 0 * * *" # Runs every day at midnight
jobs:
    scheduled-job:
        runs-on: ubuntu-latest
        steps:
            - name: Scheduled job
              run: echo "This job runs on a schedule!"
