name:  secret-reader
on:
  workflow_dispatch: 
jobs:
  secret-reader:
    runs-on: ubuntu-latest
    steps: 
        - name: prints the secrets without printing the actual value
          run: | 
            if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
              echo "The secret is set: true"
            else
              echo "The secret set is: False"
            fi 
        - name: prints the secrets with actual values
          run: echo "${{ secrets.MY_SECRET_MESSAGE }}"

        - name: Pass a secret to a step as an environment variable
          env:
            DOCKER_USERNAME: ${{vars.DOCKER_USERNAME}}
            DOCKER_PASSWORD: ${{secrets.DOCKER_PAT}}
          run: |
            echo | 
                $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin
                "Docker login successful"
