name:  secret-reader
on:
  workflow_dispatch: 
jobs:
  secret-reader:
    runs-on: ubuntu-latest
    steps: 
        - name: prints the secrets without printing the actual value
          run: | 
            if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
              echo "The secret is set: true"
            else
              echo "The secret set is: False"
            fi 
        - name: prints the secrets with actual values
          run: echo "${{ secrets.MY_SECRET_MESSAGE }}"

        - name: Pass a secret to a step as an environment variable
          run: |
            docker login -u "${{vars.DOCKER_USERNAME}}" -p "${{secrets.DOCKER_PAT}}"
            echo "Docker login successfull"
